name: Dispatch
on:
  push:
    branches:
      - master
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.dispatch_token }}
          repository: PARS-Framework/pars-master
          event-type: push-submodule
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

